/* Fichero .sql con el código de la creación de secuencias, en el caso de que se utilicen. */

CREATE SEQUENCE Seq_Jugador 
INCREMENT BY 1 
START WITH 1 
MAXVALUE 50000 
NOCACHE 
NOCYCLE;


CREATE SEQUENCE Seq_Objeto
INCREMENT BY 1 
START WITH 1 
MAXVALUE 50000 
NOCACHE 
NOCYCLE;


CREATE SEQUENCE Seq_Escenario
INCREMENT BY 1 
START WITH 1 
MAXVALUE 50000 
NOCACHE 
NOCYCLE;


CREATE SEQUENCE Seq_Evento
INCREMENT BY 1 
START WITH 1 
MAXVALUE 50000 
NOCACHE 
NOCYCLE;


CREATE SEQUENCE Seq_EventoConcreto
INCREMENT BY 1 
START WITH 1 
MAXVALUE 50000 
NOCACHE 
NOCYCLE;


CREATE SEQUENCE Seq_EventoGlobal
INCREMENT BY 1 
START WITH 1 
MAXVALUE 50000 
NOCACHE 
NOCYCLE;


CREATE SEQUENCE Seq_Enemigo
INCREMENT BY 1 
START WITH 1 
MAXVALUE 50000 
NOCACHE 
NOCYCLE;
